
export const WELCOME_MESSAGE = {
    title: 'Welcome to Shikhok',
    text: 'Shikhok is an AI-powered research notebook that helps you understand, synthesize, and interact with information from various sources. Add a source to begin.',
};

export const UI_TEXT: { [key in 'en' | 'bn']: { [key: string]: string } } = {
    en: {
        appName: 'Shikhok',
        language: 'English',
        sources: 'Sources',
        noSources: 'No sources yet.',
        clickToAdd: 'Click below to begin.',
        addSource: 'Add Source',
        notebookGuide: 'Notebook Guide',
        chat: 'Chat',
        summary: 'Summary',
        suggestedQuestions: 'Suggested Questions',
        actions: 'Actions',
        askFollowUp: 'Ask a follow-up question...',
        file: 'File',
        paste: 'Paste',
        url: 'URL',
        research: 'Research',
        uploadFile: 'Upload a File',
        addPastedText: 'Add Pasted Text',
        addUrlSource: 'Add URL Source',
        findSources: 'Find Sources',
        sourcesFound: 'Sources Found',
        addSelected: 'Add Selected Sources',
        cancel: 'Cancel',
        briefingTitle: 'Briefing Document',
        mindmapTitle: 'Mind Map',
        podcastTitle: 'Podcast Script',
        notesTitle: 'My Notes',
        download: 'Download',
        backToNotebook: 'Back to Notebook',
        save: 'Save',
        saved: 'Saved!',
        notesWarning: 'Notes are saved in this session only and will be lost on refresh.',
    },
    bn: {
        appName: 'শিক্ষক',
        language: 'Bangla',
        sources: 'উৎসসমূহ',
        noSources: 'এখনও কোন উৎস নেই।',
        clickToAdd: 'শুরু করতে নিচে ক্লিক করুন।',
        addSource: 'উৎস যোগ করুন',
        notebookGuide: 'নোটবুক গাইড',
        chat: 'চ্যাট',
        summary: 'সারসংক্ষেপ',
        suggestedQuestions: 'প্রস্তাবিত প্রশ্ন',
        actions: 'করণীয়',
        askFollowUp: 'একটি ফলো-আপ প্রশ্ন জিজ্ঞাসা করুন...',
        file: 'ফাইল',
        paste: 'পেস্ট',
        url: 'ইউআরএল',
        research: 'গবেষণা',
        uploadFile: 'ফাইল আপলোড করুন',
        addPastedText: 'পেস্ট করা টেক্সট যোগ করুন',
        addUrlSource: 'ইউআরএল উৎস যোগ করুন',
        findSources: 'উৎস খুঁজুন',
        sourcesFound: 'উৎসসমূহ পাওয়া গেছে',
        addSelected: 'নির্বাচিত উৎস যোগ করুন',
        cancel: 'বাতিল করুন',
        briefingTitle: 'ব্রিফিং ডকুমেন্ট',
        mindmapTitle: 'মাইন্ড ম্যাপ',
        podcastTitle: 'পডকাস্ট স্ক্রিপ্ট',
        notesTitle: 'আমার নোট',
        download: 'ডাউনলোড',
        backToNotebook: 'নোটবুকে ফিরে যান',
        save: 'সংরক্ষণ করুন',
        saved: 'সংরক্ষিত!',
        notesWarning: 'নোট শুধুমাত্র এই সেশনে সংরক্ষিত থাকবে এবং রিফ্রেশ করলে হারিয়ে যাবে।',
    }
};

export const ACTION_CARDS = [
    { id: 'briefing', title: 'Generate Briefing', description: 'Create a professional summary document.', icon: 'DocumentTextIcon' },
    { id: 'mindmap', title: 'Generate Mind Map', description: 'Visualize concepts hierarchically.', icon: 'MindMapIcon' },
    { id: 'podcast', title: 'Create Podcast', description: 'Draft a conversational audio script.', icon: 'FilmIcon' },
    { id: 'notes', title: 'Take Notes', description: 'Open a scratchpad for your own thoughts.', icon: 'NotesIcon' },
];
